# Generated by Django 4.2.7 on 2023-12-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=125)),
                ('country', models.CharField(max_length=125)),
                ('zipcode', models.IntegerField(max_length=10)),
            ],
        ),
    ]
