# Generated by Django 4.2.7 on 2023-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_variant_product_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='choices',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='data_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Number')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='regex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='validations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
