# Generated by Django 5.0 on 2023-12-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_property_choices_alter_property_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='properties',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='property',
            name='data_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Number'), ('choice', 'Choice')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='product.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='product.category'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(default='base', max_length=250),
        ),
    ]
