# Generated by Django 5.0 on 2024-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_variant_properties_alter_property_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='discount_percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
